# Generated by Django 5.1.7 on 2025-03-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_users_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='lodo',
        ),
    ]
