# Generated by Django 5.1.7 on 2025-04-02 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_users_email_alter_users_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='mobile_number',
        ),
    ]
